on:
  pull_request:
  push:
    branches:
    - main
name: ğŸš€ DEPLOY OFICIAL => www.lugares.ao
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy atualizado em Producao 
        uses: actions/checkout@v3

      - name: Started sync all ğŸ files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
             server: ${{ secrets.LB_server }}
             username: ${{ secrets.LB_username }}
             password: ${{ secrets.LB_password }}
             server-dir: ${{ secrets.LB_serverdir }}
             exclude: |
                **/.git*
                **/.git*/**
                **/node_modules/**