on:
  pull_request:
  push:
    branches:
    - develop
name: üöÄ DEPLOY AMBIENTE DEV => www.hml.lugares.ao
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy atualizado em dev 
        uses: actions/checkout@v3

      - name: Started sync all üéÅ files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
             server: files.000webhost.com
             username: portal-copenfl
             password: portal-copenfl
             server-dir: /public_html/
             exclude: |
                **/.git*
                **/.git*/**
                **/node_modules/**